# Generated by Django 3.1.3 on 2020-11-21 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, verbose_name='اسم المحل')),
                ('num', models.CharField(max_length=1000, verbose_name='رقم جهاز مدي')),
                ('mobile', models.CharField(max_length=1000, verbose_name='رقم الهاتف')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=10000, verbose_name='المسؤول عن القبض ')),
                ('operation_number', models.CharField(max_length=10000, unique=True, verbose_name='رقم العمليه')),
                ('deserved_amount', models.FloatField(verbose_name='المبلغ المستحق')),
                ('paid_amount', models.FloatField(verbose_name='المبلغ المدفوع')),
                ('residual', models.FloatField(verbose_name='المبلغ المتبقي')),
                ('discount', models.FloatField(verbose_name='الخصم')),
                ('bond_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ السند')),
                ('peration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ العمليه')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shop', verbose_name='المحل')),
            ],
        ),
    ]
