# Generated by Django 3.1.3 on 2020-11-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201121_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bond',
            options={'ordering': ('-bond_date',), 'verbose_name': 'سند', 'verbose_name_plural': 'السندات'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('-id',), 'verbose_name': 'محل', 'verbose_name_plural': 'المحلات'},
        ),
    ]
