# Generated by Django 3.1.3 on 2020-11-21 08:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201121_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='author',
            field=models.CharField(auto_created=True, default=django.contrib.auth.models.User, max_length=1000000),
        ),
    ]
