# Generated by Django 3.1.3 on 2020-11-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bond_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
