# Generated by Django 3.1.3 on 2020-11-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='author',
            field=models.CharField(default='objects', max_length=1000),
        ),
    ]
