# Generated by Django 3.1.3 on 2020-11-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20201121_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bond_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
