# Generated by Django 3.1.3 on 2020-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201121_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.URLField(default=False, verbose_name='كشف'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='operation_number',
            field=models.CharField(error_messages={'unique': 'عزيزي الموظف رقم العمليه مكرر يرجى مراجعة البحث وشكرا.'}, max_length=10000, unique=True, verbose_name='رقم العمليه'),
        ),
        migrations.RemoveField(
            model_name='bond',
            name='shop',
        ),
        migrations.AddField(
            model_name='bond',
            name='shop',
            field=models.ManyToManyField(to='app.Shop', verbose_name='المحل'),
        ),
    ]
